/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spellinganalysis;

import java.io.*;
import java.net.*;

import org.testng.*;
import org.testng.annotations.*;

public class MainTest {

    @Test
    public void maintest() throws URISyntaxException, IOException {
        final ClassLoader classLoader = this.getClass().getClassLoader();
        final URL resource = classLoader.getResource("test.pdf");
        final String inputPath = resource.toURI().getPath();
        final String outputPath = inputPath.substring(0, inputPath.length() - 8) + "output.txt";
        Main.main(new String[] {inputPath, outputPath});
        try (BufferedReader reader = new BufferedReader(new FileReader(new File(outputPath)))) {
            Assert.assertEquals(reader.readLine(), "Rehctschreibfehler");
        }
    }

}
